version: '3.8'

services:
  yannova-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development database (optioneel voor toekomstige features)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: yannova
      POSTGRES_USER: yannova_user
      POSTGRES_PASSWORD: yannova_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yannova_user -d yannova"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
