[build]
builder = "dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services.yannova-website]
internalPort = 3000

# Environment variables - vul deze in via Railway dashboard
[services.yannova-website.env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
